Fix warnings when compiling with MinGW GCC 8.1.0
*** Warning 1 ***
format '%u' expects argument of type 'unsigned int', but argument 3 has type 'DWORD' {aka 'long unsigned int'} [-Werror=format=]

*** Warning 2 ***
import/fathom/tbprobe.c:181: error: "max" redefined [-Werror]
 #define max(a,b) a > b ? a : b

In file included from C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from import/fathom/tbprobe.c:62:
C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/minwindef.h:173: note: this is the location of the previous definition
 #define max(a, b) (((a) > (b)) ? (a) : (b))

*** Warning 3 ***
import/fathom/tbprobe.c:182: error: "min" redefined [-Werror]
 #define min(a,b) a < b ? a : b

In file included from C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from import/fathom/tbprobe.c:62:
C:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/x86_64-w64-mingw32/include/minwindef.h:177: note: this is the location of the previous definition
 #define min(a, b) (((a) < (b)) ? (a) : (b))